### ISSUE TITLE
improve approach to determining API table schema

### ISSUE THREAD

**Issue by damonmcc** [NYCPlanning/ae-data-flow#43]

**Comment by TangoYankee** [comment]
From #57, we ended up using a combination of [`drizzle-kit` introspection](https://orm.drizzle.team/docs/get-started/mysql-existing#step-4---introspect-your-database) and [`pg_dump`](https://www.postgresql.org/docs/current/app-pgdump.html). Drizzle kit handles the enums. pg_dump handles the rest of the schemas.
