### ISSUE TITLE
Capital Planning ETL

### ISSUE THREAD

**Issue by TangoYankee** [NYCPlanning/ae-data-flow#53]
# Description
Add capital planning to the ETL

## Acceptance criteria
- [ ] Capital planning data is loaded into db for NYCPlanning/ae-zoning-api

**Comment by TangoYankee** [comment]
@damonmcc AE & DE collaborate on file sources (with emphasis on zoning-districts)

**Comment by damonmcc** [comment]
@TangoYankee if the changes are working well enough for you, let's merge your PR https://github.com/NYCPlanning/ae-data-flow/pull/52

after that I'll work on sourcing zoning districts and any other helpful refinements (like the new test github action you made, aligning github actions with the local approach, etc.)

**Comment by damonmcc** [comment]
per AE sprint planning today: @TangoYankee will split up the changes in #52 this sprint

**Comment by TangoYankee** [comment]
Discussion #56
